export const WINDOW_ON_RESIZE = 'WINDOW_ON_RESIZE'
// settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const SAVE_LOG = 'SAVE_LOG'
export const CLEAR_LOG = 'CLEAR_LOG'
export const RESET_SETTINGS = 'RESET_SETTINGS'
// template
export const UPDATE_TEMPLATE_SETTINGS = 'UPDATE_TEMPLATE_SETTINGS'
export const UPDATE_TEMPLATE_LIST = 'UPDATE_TEMPLATE_LIST'
export const MERGE_TEMPLATE_LIST = 'MERGE_TEMPLATE_LIST'
// project
export const ADD_PROJECT = 'ADD_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const MERGE_PROJECT_LIST = 'MERGE_PROJECT_LIST'
export const UPDATE_SELECT_INDEX = 'UPDATE_SELECT_INDEX'

// project tables action
export const ADD_PROJECT_TABLE = 'ADD_PROJECT_TABLE'
export const DELETE_PROJECT_TABLE = 'DELETE_PROJECT_TABLE'
export const UPDATE_PROJECT_TABLE = 'UPDATE_PROJECT_TABLE'
export const UPDATE_ON_EDIT_TABLE_INDEX = 'UPDATE_ON_EDIT_TABLE_INDEX'
